compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider:
  win: azure
  linux_aarch64: default
  linux_ppc64le: default
build_platform:
  osx_arm64: osx_64
conda_forge_output_validation: true
test_on_native_only: True
upload_on_branch: master
