travis:
  secure:
    BINSTAR_TOKEN: wHuOrqjvrzN3N+96BHnv2HBI5q75VSTRmptRCKHpj2Y3ICfBSKaSydz7bU8ISzHMflyH/5fy9bD7iBiTAlCRJNzpu7+f0tL4DKxdU5Ibz5DkWqxV8As1swi/jhxmRXtl6tpJGRJ7fYQQzm8HWFYDh4TPUivh9s/YFYPFWVs9ZoRgeMFWXhjNwcrwtaGdSslNl/A8BV/33WRu8Getj8h+rwkvtOaBYUmDdaXk8Ihuw+oIR51cNaHGXAob7dBWGgP0IKGWrCKqiLaCylX6vwHdwI7Laz3kfgKiJsAkHlKKQH00VDZWDzm5P8mtkVq6BXKXrIt5jm7pBE+oUfpgme1ZScyP30PjxY7lg/MdhcXo6Uc2865boFHfpINhTr8cBRTAGae3JUxumf7heu3hjTBDZRMsBGaXhLXwhYrnRSnbXHbt2/Sz+js1WG5MD/zA996s0DCSqf+j8nf1oq+MqbW1VQOJsT3yO2eCT50Bk5q3EbmMXDK2e27nsSaw2Id08nLAmWAUFX5bBxJhF0LpWWPK+ySC1v4xiNdbtFuwmwn/uhKWnrJ1vsK4sOmeaV6gssM2UwzS6YgkZF2A/o7eOmFrkb0ExX2KeesrWnQ5PHlZTW/ieJsN0jBzzmFmgkrXFD76N21bYBBLzbV3uIcFDTVdjdUrOwS28+X8oGpn2fDb/y8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
